name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-20.04
    env:
      COMPILER: x86_64-w64-mingw32-gcc -Iomicron/external/include/ddk
      UNAME: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Requirements
        run: |
          git clone --branch=v2.5 --depth=1 https://github.com/uic-evl/omicron.git omicron
          sudo apt-get -y update
          sudo apt-get -y install libudev-dev
          sudo apt-get install gcc-mingw-w64

      - name: Compile
        run: |
          make all

      - name: List Results
        run: |
          ls -r .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: edbg-windows
          path: edbg.exe

      - name: Upload Binary
        run: |
          RESPONSE=`curl -T edbg.exe -u${{secrets.CD_AUTH}} ${{secrets.CD_SERVER}}/edbg/${{github.run_number}}/edbg-windows-r${{github.run_number}}.exe`
          if [ 'OK' != "${RESPONSE}" ]; then
            echo "Depolyment to failed with response ${RESPONSE}";
            exit 1;
          fi

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Requirements
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libudev-dev

      - name: Compile
        run: |
          make all

      - name: List Results
        run: |
          ls -r .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: edbg-linux
          path: edbg

      - name: Upload Binary
        run: |
          RESPONSE=`curl -T edbg -u${{secrets.CD_AUTH}} ${{secrets.CD_SERVER}}/edbg/${{github.run_number}}/edbg-linux-r${{github.run_number}}`
          if [ 'OK' != "${RESPONSE}" ]; then
            echo "Depolyment to failed with response ${RESPONSE}";
            exit 1;
          fi

  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Requirements
        run: |
          brew install hidapi;

      - name: Check requirements
        run: |
          brew list --versions hidapi
          brew info hidapi

      - name: Compile
        run: |
          make all

      - name: List Results
        run: |
          ls -r .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: edbg-macos
          path: edbg

      - name: Upload Binary
        run: |
          RESPONSE=`curl -T edbg -u${{secrets.CD_AUTH}} ${{secrets.CD_SERVER}}/edbg/${{github.run_number}}/edbg-mac-r${{github.run_number}}`
          if [ 'OK' != "${RESPONSE}" ]; then
            echo "Depolyment to failed with response ${RESPONSE}";
            exit 1;
          fi


